apiVersion: v1 # 해당 리소스가 사용할 k8s api 버전
kind: Service # 생성할 리소스의 타입을 정의
metadata: # 리소스에 대한 메타데이터 정의 부분
  name: {{.Values.name}}-service # Service의 이름 정의
  namespace: {{.Values.namespace}} # Service가 속할 네임스페이스 정의
spec: # Service의 세부사항 정의
  type: {{.Values.service.type}} # Service의 타입 정의 ClusterIP, NodePort, LoadBalancer
  selector: # 이 Service가 연결할 파드를 선택하는 기준 정의
    app: {{.Values.name}} # app이라는 라벨이 {{.Values.name}}과 일치하는 파드 선택
  ports: # Service에서 사용할 포트 설정
  - protocol: TCP # 통신 프로토콜 정의
    port: {{.Values.service.port}} # 클라이언트가 Service 호출 시 사용할 포트 번호 정의 (서비스의 포트라고 생각하자)
    targetPort: {{.Values.service.targetPort}} # 서비스가 선택한 파드의 내부에서 트래픽을 전달할 컨테이너의 포트(컨테이너의 포트라고 생각하자)
    # 즉, 클라이언트가 port를 통해 요청을 보내면, 해당 요청은 port -> targetPort로 port forwarding 되는 것
