version: "3.8"

services:
  bgjg_db:
    image: postgres:15
    ports:
      - 5432:5432
    # volumes:
    #   - host경로:container경로
    env_file:
      - ./.env.db
    container_name: bgjg_postgres
    restart: always

  bgjg_api_server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: bgjg_api_server
    ports:
      - 80:3000
    env_file:
      - ./.env.local
    depends_on:
      - bgjg_db
    command: npm run start:prod
